### ISSUE TITLE
Problems with data

### ISSUE THREAD

**Issue by Luca7993** [btodcox/BBQduino#2]
Hi,
i'm trying to use a similar solution with my maverick 732 but I have some problems with received data:

in BBQ_packet_process I receive sometimes the correct AA 99 95 (and in this case the probe temperature are ok), and sometimes other data that do not start with AA 99 95 but with random characters.
do you know if could be a problem of the receiver or with antenna or what else?

**Comment by btodcox** [comment]
There are numerous sources of bad data that I have seen.   However, it is not unusual to see bad packets; this is why the transmitter sends the same data 3 times in a row and there is a checksum to validate packets.

My personal experiences:
* Bad receiver. 
* Wrong length antenna (mainly affected reception distance).
* 433MHz can be rather congested with other devices using the frequency.  Most consumer grade devices transmit without checking to see if the frequency is in use resulting in a garbage packets when more than one device is transmitting.
* Low batteries in transmitter.
* One transmitter I had drifted far enough off 433MHz that not even the Maverick brand receiver could interpret the data.

One thing that might be worth trying is probing the data as it is received by a Maverick receiver to better isolate what you are seeing.   It has been a while since I have opened one up, but I seem to recall that the receiver board inside a Maverick receiver was separate with four clearly labeled pins that connect to the microcontroller board.   Using a USB logic analyzer with Manchester decoding software (e.g., Saleae) could help in locating exactly what is going on in your situation.
